POST https://api.twitter.com/oauth/request_token
Authorization: OAuth oauth_nonce="1", oauth_callback="http%3A%2F%2Fmyapp.com%3A3005%2Ftwitter%2Fprocess_callback", oauth_signature_method="HMAC-SHA1", oauth_timestamp="${{$timestamp}}", oauth_consumer_key="nvQvzjkVQYagpijRzZIsQ", oauth_signature="r3xtESAVMZu4uHDDDOKEbXew3RX1cvL2k7lsgZoOE", oauth_version="1.0"