POST  https://api.twitter.com/oauth/request_token
User-Agent: themattharris HTTP Client
Accept: */*
Authorization: OAuth oauth_callback="http%3A%2F%2Flocalhost%3A8080%2Fjw%2Fweb%2Fjson%2Fplugin%2Forg.joget.twitter.TwitterSecurity%2Fservice", oauth_consumer_key="nvQvzjkVQYagpijRzZIsQ", oauth_nonce="{{$guid}}", oauth_signature="r3xtESAVMZu4uHDDDOKEbXew3RX1cvL2k7lsgZoOE", oauth_signature_method="HMAC-SHA1", oauth_timestamp="{{$timestamp}}", oauth_version="1.0"


https://edoc.ku.ac.th/index.html